export const OPENPOPUP ='OPENPOPUP';
export const OUTBOUNDFLIGHTS = 'OUTBOUNDFLIGHTS'
export const SERVICECALLFAILEDINSEARCHRESULTS= 'SERVICECALLFAILEDINSEARCHRESULTS'
export const LANGUAGECONTENT ="LANGUAGECONTENT"
export const SERVICECALLFAILEDINLANGUAGECONTENT= 'SERVICECALLFAILEDINLANGUAGECONTENT'